name: local_data_source
description: Simple local data source wrap of hive.
version: 1.0.0
homepage: https://github.com/ansabic/LocalDataSource

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


